### ISSUE TITLE
Create a repo and diagram for nginx-aws-signature

### ISSUE THREAD

**Issue by shawndotkim** [nginxinc/nginx-aws-signature#2]
### Is your feature request related to a problem? Please describe

As a SWE,
I want to reuse a `nginx-aws-signature` library for accessing several AWS services such as S3 and Lambda via NGINX.

### Describe the solution you'd like
- Create a repo of `nginx-aws-signature`.
- Create a diagram of `nginx-aws-signature`.

### Describe alternatives you've considered

- First approach is to implement the library per each repo such as `nginx-s3-gateway` and `nginx-lambda-gateway`.
- Second approach is to consolidate the common library for accessing several AWS services.

### Additional context

- N/A

**Comment by shawnhankim** [comment]
Closed
